---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demon-lab
spec:
  selector:
    matchLabels:
      app: monitor
  template:
      metadata:
        labels:
          app: monitor
      spec:
        containers:
          - name: container1
            image: nginx
            ports:
              - containerPort: 80

