---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: liveness
    image: nginx
    args:
    - /bin/sh
    - -c
    - touch /tmp/santosh; sleep 300
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/santosh
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 30
